// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.ceit.desktop.grpc.caCenter;

public final class CAProto {
  private CAProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceRegisteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceRegisteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceUnRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceUnRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceUnRegisteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceUnRegisteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_SoftRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_SoftRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_SoftRegisteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_SoftRegisteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caCenter_DeviceCheckReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caCenter_DeviceCheckReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014device.proto\022\010caCenter\"o\n\025DeviceRegist" +
      "erRequest\022\021\n\tis_handle\030\001 \001(\005\022\016\n\006serial\030\002" +
      " \001(\t\022\020\n\010dev_name\030\003 \001(\t\022\016\n\006org_id\030\004 \001(\t\022\021" +
      "\n\tdevice_ip\030\005 \001(\t\"=\n\022DeviceRegisteReply\022" +
      "\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\014\n\004data\030\003 \001(\t" +
      "\"?\n\027DeviceUnRegisterRequest\022\020\n\010username\030" +
      "\001 \001(\t\022\022\n\ndevica_mac\030\002 \001(\t\"C\n\024DeviceUnReg" +
      "isteReply\022\016\n\006status\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\016" +
      "\n\006result\030\003 \001(\t\"(\n\023SoftRegisterRequest\022\021\n" +
      "\tsoft_Hash\030\001 \001(\t\"?\n\020SoftRegisteReply\022\016\n\006" +
      "status\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\016\n\006result\030\003 \001(" +
      "\t\";\n\022DeviceCheckRequest\022\022\n\ndeviceHash\030\001 " +
      "\001(\t\022\021\n\tdevice_ip\030\002 \001(\t\"?\n\020DeviceCheckRep" +
      "ly\022\016\n\006status\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\022\016\n\006resul" +
      "t\030\003 \001(\t2\316\002\n\010CaCenter\022Q\n\016DeviceRegister\022\037" +
      ".caCenter.DeviceRegisterRequest\032\034.caCent" +
      "er.DeviceRegisteReply\"\000\022W\n\020DeviceUnRegis" +
      "ter\022!.caCenter.DeviceUnRegisterRequest\032\036" +
      ".caCenter.DeviceUnRegisteReply\"\000\022K\n\014Soft" +
      "Register\022\035.caCenter.SoftRegisterRequest\032" +
      "\032.caCenter.SoftRegisteReply\"\000\022I\n\013DeviceC" +
      "heck\022\034.caCenter.DeviceCheckRequest\032\032.caC" +
      "enter.DeviceCheckReply\"\000B1\n\036com.ceit.des" +
      "ktop.grpc.caCenterB\007CAProtoP\001\242\002\003HLWb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_caCenter_DeviceRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_caCenter_DeviceRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceRegisterRequest_descriptor,
        new String[] { "IsHandle", "Serial", "DevName", "OrgId", "DeviceIp", });
    internal_static_caCenter_DeviceRegisteReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_caCenter_DeviceRegisteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceRegisteReply_descriptor,
        new String[] { "Code", "Msg", "Data", });
    internal_static_caCenter_DeviceUnRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_caCenter_DeviceUnRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceUnRegisterRequest_descriptor,
        new String[] { "Username", "DevicaMac", });
    internal_static_caCenter_DeviceUnRegisteReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_caCenter_DeviceUnRegisteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceUnRegisteReply_descriptor,
        new String[] { "Status", "Msg", "Result", });
    internal_static_caCenter_SoftRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_caCenter_SoftRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_SoftRegisterRequest_descriptor,
        new String[] { "SoftHash", });
    internal_static_caCenter_SoftRegisteReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_caCenter_SoftRegisteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_SoftRegisteReply_descriptor,
        new String[] { "Status", "Msg", "Result", });
    internal_static_caCenter_DeviceCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_caCenter_DeviceCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceCheckRequest_descriptor,
        new String[] { "DeviceHash", "DeviceIp", });
    internal_static_caCenter_DeviceCheckReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_caCenter_DeviceCheckReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caCenter_DeviceCheckReply_descriptor,
        new String[] { "Status", "Msg", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
