// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.ceit.desktop.grpc.caCenter;

public interface DeviceCheckReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:caCenter.DeviceCheckReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string result = 3;</code>
   * @return The result.
   */
  String getResult();
  /**
   * <code>string result = 3;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
