// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.ceit.desktop.grpc.caCenter;

public interface DeviceCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:caCenter.DeviceCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceHash = 1;</code>
   * @return The deviceHash.
   */
  String getDeviceHash();
  /**
   * <code>string deviceHash = 1;</code>
   * @return The bytes for deviceHash.
   */
  com.google.protobuf.ByteString
      getDeviceHashBytes();

  /**
   * <code>string device_ip = 2;</code>
   * @return The deviceIp.
   */
  String getDeviceIp();
  /**
   * <code>string device_ip = 2;</code>
   * @return The bytes for deviceIp.
   */
  com.google.protobuf.ByteString
      getDeviceIpBytes();
}
