// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

package com.ceit.desktop.grpc.caCenter;

public interface SoftRegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:caCenter.SoftRegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string soft_Hash = 1;</code>
   * @return The softHash.
   */
  String getSoftHash();
  /**
   * <code>string soft_Hash = 1;</code>
   * @return The bytes for softHash.
   */
  com.google.protobuf.ByteString
      getSoftHashBytes();
}
